### ISSUE TITLE
Why not tea?

### ISSUE THREAD

**Issue by NathanPB** [Cafeteria-OSS/cafeteria.js#2]
fuck coffees, those are overrated

**Comment by CaelTheColher** [comment]
go drink a beer lmao

**Comment by allanf181** [comment]
![image](https://user-images.githubusercontent.com/14101716/78149870-e0502600-740c-11ea-8445-4b422c7d3539.png)
is better

**Comment by adriantodt** [comment]
Tea is WIP and will be available on the next update.

**Comment by NathanPB** [comment]
> go drink a beer lmao

im not gonna drink limão 😡
